# Generated by Django 4.1 on 2022-08-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncaa', '0002_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
