# Generated by Django 4.1 on 2022-08-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncaa', '0004_player_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
