# Generated by Django 4.1 on 2022-08-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncaa', '0005_delete_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
